### ISSUE TITLE
Tracking bug: Integration of Array in JAX.

### ISSUE THREAD

**Issue by yashk2810** [google/jax#12016]
- [x] Add tests for _committed attribute in Array.

- [x] Figure out how to resolve the local imports like (from jax.experimental import pjit) that are in dispatch.py.

- [x] Make testArrayCopy in lax_numpy_test.py work with Array. There is a TODO in that test with this bug number.

- [x] Make xmap work properly with SingleDeviceSharding Arrays or just make the behavior of xmap similar to what it was with DA and SDA.
- [x] Implement no copy indexing similar to SDA i.e. __getitem__ of SDA
- [x] Make sure that non-committed Arrays on SingleDevice (for eg. jnp.arange(10) with a mesh decorator are sharded properly in pjit and xmap.
- [x] Add a similar check to non-XLACompatibleShardings that exists in the constructor of Array (there is a TODO there).

**Comment by yashk2810** [comment]
4. Make xmap work properly with SingleDeviceSharding Arrays or just make the behavior of xmap similar to what it was with DA and SDA.

**Comment by yashk2810** [comment]
5. Implement no copy indexing similar to SDA.

**Comment by mjsML** [comment]
I think this would be much better using the GitHub projects / boards feature :)

**Comment by yashk2810** [comment]
6. Make sure that non-committed Arrays on SingleDevice (for eg. jnp.arange(10) with a mesh decorator are sharded properly in pjit and xmap.

**Comment by yashk2810** [comment]
7. Make Array work properly with `view = jnp.array(buf, copy=False)` so that `buf.unsafe_buffer_pointer() == view.unsafe_buffer_pointer())`

**Comment by yashk2810** [comment]
I have moved other things to this board: https://github.com/orgs/google/projects/25/views/1 but I am keeping this bug alive for the things I am tracking here.

**Comment by yashk2810** [comment]
Because the boards can only be created at the project IIUC. If there is a different solution, I can use that :)
