### ISSUE TITLE
Tracking bug: jit pjit frontend merge

### ISSUE THREAD

**Issue by yashk2810** [google/jax#13670]
- [ ] Add support for inline to pjit
- [ ] Support dynamic shapes in the lowering and compilation paths when jax.Array is enabled
- [ ] Add abstracted_axes support to pjit
- [ ] Make execute_sharded_on_local_devices accept Array rather than DeviceBuffers
- [ ] Remove usage of `_arrays` from jax internal code
