### ISSUE TITLE
Tracking issue: NumPy 2.0 Compatibility

### ISSUE THREAD

**Issue by jakevdp** [google/jax#19246]
NumPy 2.0 is coming, and there are a number of things we need to do to ensure a smooth transition for users. This issue tracks these TODOs. Relevant NumPy issue is here: https://github.com/numpy/numpy/issues/24300.

This has some overlap with #18353, as NumPy is aiming for array API compatibility in v2.0.

- [x] add an upstream nightly build (kokoro only, because of jaxlib build requirement)
- [x] fix `np.ComplexWarning` references (#19245)
- [x] new `sign` convention for complex entries (#19390)
- [x] fix `jax.scipy.special.logsumexp` for new sign convention (#19389)
- [x] New shape for `inverse_indices` in `jnp.unique` (#19320)
- [x] add new `jax.numpy` functions:
  - [x] `concat` #19323
  - [x] `isdtype` #19400
  - [x]  `permute_dims` #19244
  - [x] `bitwise_invert` #19278
  - [x] `bitwise_left_shift` #19278
  - [x] `bitwise_right_shift` #19278
  - [x] `pow` #19293
  - [x] `vecdot` #19274

Fix some relevant bugs in NumPy & SciPy:
- [x] https://github.com/numpy/numpy/issues/25553
- [x] https://github.com/numpy/numpy/pull/25554
- [x] https://github.com/numpy/numpy/pull/25560
- [x] https://github.com/scipy/scipy/pull/19870

Once there is a NumPy 2.0 release candidate, we should do an `ml_dtypes` and `jaxlib` release built against that candidate; these should be compatible with numpy versions back to our minimum supported version.

**Comment by jakevdp** [comment]
We're in good shape here; the only failures as of today are fft bugs upstream (https://github.com/numpy/numpy/issues/25661 and https://github.com/numpy/numpy/issues/25679). These are being fixed in https://github.com/numpy/numpy/pull/25668

Beyond that, our main TODO is to update our builds to use the numpy 2.0 ABI once the release candidates are out.

**Comment by hawkinsp** [comment]
I think we can declare this fixed. We've made a release with NumPy 2.0, which was the last main TODO.
