### ISSUE TITLE
v0.2 tasks

### ISSUE THREAD

**Issue by alexbw** [google/jax#57]
Collecting issues for a hypothetical v0.2.

- [x] easy API for custom primitives (w/ docs) (#116)
- [x] Experimental Cloud TPU support (#27)
- [x] Frequently asked questions doc (#58)
- [x] Autodiff cookbook (#59)
- [ ] Vmap cookbook (#60)
- [x] api.py documentation (#61)
- [x] Upload some materials to docs folder (e.g. PRNG design doc, rev-from-fwd) (#62)
- [ ] JAX development philosophy doc (#64)
~- [ ] Rename jaxlib to xlapy (#65)~
- [ ] Conda installations (#66)
- [ ] ~Full~ Good NumPy core function coverage (#70)
- [x] Full np.fft coverage
- [x] Full np.linalg coverage
- [x] ~Full np.random~ Good random coverage
- [x] grad of cond and while (#83)
- [ ] mature stax (#137)
- [ ] JAX + TF interop (demonstrates composability with internal end external tools) (#45)
- [x] In-place update syntax (#122)
- [x] Keras NumPy backend demo (#63)
- [x] Open source tests (#67)
- [x] ONNX -> jaxpr loading (#91)
- [x] Travis CI (#68)

**Comment by hawkinsp** [comment]
This is our oldest issue. I think we might have done everything on the list at this point, or chosen not to do it (except for a couple of the proposed documentation issues).

Closing because clearly this issue isn't really governing our version numbering plans at this point...
